spring:
  application:
    name: unBlock_Group_servers
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: Ntmtrung1973@

server:
  address: 0.0.0.0
  port: 8080
  error:
    include-exception: true
    include-message: always
